name: shopping_list_env
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - streamlit
    - pandas
    - google-api-python-client==2.89.0
    - google-auth
    - google-auth-oauthlib
