name: shopping_list_env
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - requests
  - certifi
  - urllib3 # Added to ensure clean network stack
  - pip:
    - streamlit
    - pandas
    - google-api-python-client
    - google-auth
    - google-auth-oauthlib
