name: shopping_list_env
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - requests
  - certifi
  - urllib3=1.26.0 # Updated pin
  - cryptography
  - pip:
    - streamlit
    - pandas
    - google-api-python-client
    - google-auth
    - google-auth-oauthlib
