name: shopping_list_env
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - requests
  - certifi
  - urllib3
  - cryptography # Added to ensure robust TLS/SSL support
  - pip:
    - streamlit
    - pandas
    - google-api-python-client
    - google-auth
    - google-auth-oauthlib
