name: shopping_list_env
channels:
  - defaults
dependencies:
  - python=3.10 # Reverting to a previously tested version
  - pip
  - requests
  - certifi
  - urllib3
  - cryptography
  - pip:
    - streamlit
    - pandas
    - google-api-python-client
    - google-auth
    - google-auth-oauthlib
