name: shopping_list_env
channels:
  - defaults
dependencies:
  - python=3.9 # Reverting to the version often used by Streamlit Cloud
  - pip
  - pip:
    - streamlit
    - pandas
    - google-api-python-client
    - google-auth
    - google-auth-oauthlib
