name: shopping_list_env
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - requests=2.27.1  # Pinning a stable requests version
  - urllib3=1.26.9   # Pinning a compatible urllib3 version
  - pip:
    - streamlit
    - pandas
    - google-api-python-client==2.89.0
    - google-auth
    - google-auth-oauthlib
