name: shopping_list_env
channels:
  - defaults
dependencies:
  - python=3.8 # CHANGED TO 3.8
  - pip
  - requests
  - certifi
  - urllib3
  - cryptography
  - pip:
    - streamlit
    - pandas
    - google-api-python-client
    - google-auth
    - google-auth-oauthlib
